// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BackupTemplates() {
  return window['go']['main']['App']['BackupTemplates']();
}

export function CheckConnection() {
  return window['go']['main']['App']['CheckConnection']();
}

export function ConnectSSH(arg1, arg2) {
  return window['go']['main']['App']['ConnectSSH'](arg1, arg2);
}

export function DeleteConfig() {
  return window['go']['main']['App']['DeleteConfig']();
}

export function DisconnectSSH() {
  return window['go']['main']['App']['DisconnectSSH']();
}

export function FetchTemplates() {
  return window['go']['main']['App']['FetchTemplates']();
}

export function GenerateSSHKey() {
  return window['go']['main']['App']['GenerateSSHKey']();
}

export function GetConfigPath() {
  return window['go']['main']['App']['GetConfigPath']();
}

export function GetVersion() {
  return window['go']['main']['App']['GetVersion']();
}

export function IsConnected() {
  return window['go']['main']['App']['IsConnected']();
}

export function ListSSHKeys() {
  return window['go']['main']['App']['ListSSHKeys']();
}

export function LoadConfig() {
  return window['go']['main']['App']['LoadConfig']();
}

export function RebootDevice() {
  return window['go']['main']['App']['RebootDevice']();
}

export function SaveConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveConfig'](arg1, arg2);
}

export function SelectTemplateFile() {
  return window['go']['main']['App']['SelectTemplateFile']();
}

export function SyncTemplates(arg1, arg2) {
  return window['go']['main']['App']['SyncTemplates'](arg1, arg2);
}

export function UploadSSHKey(arg1, arg2, arg3) {
  return window['go']['main']['App']['UploadSSHKey'](arg1, arg2, arg3);
}
