// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function BackupTemplates():Promise<string>;

export function CheckConnection():Promise<void>;

export function ConnectSSH(arg1:string,arg2:string):Promise<void>;

export function DisconnectSSH():Promise<void>;

export function FetchTemplates():Promise<Array<main.DeviceTemplate>>;

export function GenerateSSHKey():Promise<main.SSHKey>;

export function GetVersion():Promise<string>;

export function IsConnected():Promise<boolean>;

export function ListSSHKeys():Promise<Array<main.SSHKey>>;

export function RebootDevice():Promise<void>;

export function SelectTemplateFile():Promise<main.SelectedFile>;

export function SyncTemplates(arg1:Array<main.SyncTemplate>,arg2:Array<string>):Promise<void>;

export function UploadSSHKey(arg1:string,arg2:string,arg3:string):Promise<void>;
